Don't include .h files
Getting a weird zig error:

error: unknown file type for an object file
    note: while parsing /Users/kll/dt/acton-deps/tlsuv/.zig-cache/o/06358706310483a9162b1416445cd82c/um_debug.o

Took a while to figure out it is because of inclusion of .h. I wonder
what it really does.